const { chromium } = require(process.env.PLAYWRIGHT_MODULE || "playwright");
const assert = require("node:assert/strict");
(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: process.env.BROWSER_PATH || "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe" });
  try {
    const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
    const errors = []; page.on("pageerror", e => errors.push(e.message));
    const base = process.env.BASE_URL || "http://127.0.0.1:3010";
    await page.goto(base + "/lessons/001");
    await page.getByText("心理训练 · 目标、重置与复盘", { exact: true }).click();
    await page.getByLabel("今天的过程目标").fill("失误后回到大区");
    await page.getByLabel("我的重置提示词").fill("看球，打大区");
    await page.getByRole("button", { name: "完成一次重置 +1" }).click();
    await page.getByRole("button", { name: "完成一次重置 +1" }).click();
    await page.getByRole("button", { name: "撤销一次重置" }).click();
    await page.getByLabel("课后反思 / 下次行动").fill("下次继续关注大目标");
    await page.reload();
    await page.getByRole("button", { name: "进入带课模式" }).click();
    assert.equal(await page.getByLabel("今天的过程目标").inputValue(), "失误后回到大区");
    await page.getByText(/本次已完成重置 1 次/).waitFor();
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({ path: "../tmp/pdfs/mental-mobile.png" });
    await page.getByRole("button", { name: "保存并结束本次课" }).click();
    assert.equal(await page.getByLabel("今天的过程目标").inputValue(), "");
    const store = await page.evaluate(() => JSON.parse(localStorage.getItem("tennis-coach-workspace-v2")));
    assert.equal(store.history[0].mental.resets, 1);
    assert.equal(store.history[0].mental.reflection, "下次继续关注大目标");
    await page.goto(base + "/lessons#records");
    await page.getByText("过程目标：失误后回到大区", { exact: true }).waitFor();
    const downloading = page.waitForEvent("download");
    await page.getByRole("button", { name: "备份全部记录" }).click();
    const file = await downloading, fs = require("node:fs");
    const exported = JSON.parse(fs.readFileSync(await file.path(), "utf8"));
    assert.equal(exported.history[0].mental.goal, "失误后回到大区");
    await page.evaluate(() => localStorage.removeItem("tennis-coach-workspace-v2"));
    await page.reload();
    await page.getByLabel("选择记录备份文件").setInputFiles({ name: "mental.json", mimeType: "application/json", buffer: Buffer.from(JSON.stringify(exported)) });
    await page.getByRole("button", { name: "合并这份备份" }).click();
    await page.getByText("复盘：下次继续关注大目标", { exact: true }).waitFor();
    const invalid = JSON.parse(JSON.stringify(exported)); invalid.history[0].mental.resets = -1;
    await page.getByLabel("选择记录备份文件").setInputFiles({ name: "bad.json", mimeType: "application/json", buffer: Buffer.from(JSON.stringify(invalid)) });
    await page.getByText(/无法读取：/).waitFor();
    const old = JSON.parse(JSON.stringify(exported));
    old.history.forEach(h => delete h.mental); Object.values(old.records).forEach(r => delete r.draft.mental);
    await page.getByLabel("选择记录备份文件").setInputFiles({ name: "old.json", mimeType: "application/json", buffer: Buffer.from(JSON.stringify(old)) });
    await page.getByRole("button", { name: "合并这份备份" }).click();
    await page.goto(base + "/lessons/001");
    await page.getByRole("button", { name: "进入带课模式" }).click();
    assert.equal(await page.getByLabel("今天的过程目标").inputValue(), "");
    await page.getByRole("button", { name: "完成一次重置 +1" }).click();
    await page.getByText(/本次已完成重置 1 次/).waitFor();
    assert.deepEqual(errors, []);
    console.log("PASS mental: draft persistence, reset undo, class archive, fresh next draft, backup roundtrip, invalid payload rejection, old backups and mobile layout.");
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
